from .thg_arquivo.arquivo import Arquivos
from .thg_baixar.baixar import Baixar
from .thg_convert.convert import Convert
from .thg_cores.conf_colors import *
from .thg_cores.cores import Cores
from .thg_debug.debug import Debug
from .thg_decode.conf_decode import *
from .thg_decode.decode import Decode
from .thg_encode.conf_encode import *
from .thg_encode.encode import Encode
from .thg_hash_encode.hash_encode import Hash_encode
