site_name: thg
site_url: https://github.com/darkcode357/thg_lib
site_description: documentacao do thg_lib
site_author: darkcode0x00
repo_url: https://github.com/darkcode357/thg_lib
heme:
    name: mkdocs
    shortcuts:
        help: 1    # ?
        next: 7     # n
        previous: 8 # p
        search: 8   # s

markdown_extensions:
- toc:
      permalink: '#'
extra:
    theme_inverse: true
# Copyright
copyright: "Copyright &copy; 2019 THG_lib Project by darkcode"
nav:
- Overview:
  - Installation: ./cli/install.md
  - Introduction: index.md
  - Community: community.md
  - Conceptual: conceptual.md

- capture the flag:
  - basic:
    - identify:
      - basic: ./capturetheflag/basic/identify/basic.md
      - nmap: ./capturetheflag/basic/identify/nmap.md
      - nessus: ./capturetheflag/basic/identify/nessus.md
      - openvas: ./capturetheflag/basic/identify/openvas.md
      - windows: ./capturetheflag/basic/identify/windows.md
      - linux: ./capturetheflag/basic/identify/linux.md
    - defend:
      - windows: ./capturetheflag/basic/prootect_defend/windows.md
      - linux: ./capturetheflag/basic/prootect_defend/linux.md
    - identify:
      - tcpdump: ./capturetheflag/basic/detect/tcpdump.md
      - edicap: ./capturetheflag/basic/detect/editcap.md
      - mergecap: ./capturetheflag/basic/detect/mergecap.md
      - snort: ./capturetheflag/basic/detect/snort.md
      - tshark: ./capturetheflag/basic/detect/tshark.md
      - analysis: ./capturetheflag/basic/detect/analysis.md
      - os:
        - linux: ./capturetheflag/basic/detect/linux.md
        - windows: ./capturetheflag/basic/detect/windows.md
    - analysis:
      - malware: ./capturetheflag/basic/analysis/malware.md
      - linux: ./capturetheflag/basic/analysis/linux.md
      - windows: ./capturetheflag/basic/analysis/windows.md
    - Deployment: deployment.md



- CLI:
  - THG-PART-1:
    - THG: ./tutorials/thg.md
    - thg_server: ./tutorials/thg_server.md
    - thg_version: ./tutorials/thg_version.md
    - thg_shells: ./tutorials/thg_shells.md
    - thg_docs:  ./tutorials/thg_docs.md
    - thg_auxiliares: ./tutorials/thg_auxiliares.md
    - thg_anti_forensic: ./tutorials/thg_anti_forensic.md
    - thg_crypto: ./tutorials/thg_crypto.md
    - thg_drone: ./tutorials/thg_drone.md
    - thg_keylogger: ./tutorials/thg_keylogger.md
    - thg_recon: ./tutorials/thg_recon.md
    - thg_voip: ./tutorials/thg_voip.md
    - thg_automation: ./tutorials/thg_automation.md
    - thg_cryptography: ./tutorials/thg_cryptography.md
    - thg_exploitation: ./tutorials/thg_exploitation.md
    - thg_malware: ./tutorials/thg_malware.md
    - thg_reversing: ./tutorials/thg_reversing.md
    - thg_windows: ./tutorials/thg_windows.md
    - thg_automobile: ./tutorials/thg_automobile.md
    - thg_database: ./tutorials/thg_database.md
    - thg_fingerprint: ./tutorials/thg_fingerprint.md
    - thg_misc: ./tutorials/thg_misc.md
    - thg_sniffer: ./tutorials/thg_sniffer.md
    - thg_wireless: ./tutorials/thg_wireless.md
    - thg_debugger: ./tutorials/thg_debugger.md
    - thg_firmware: ./tutorials/thg_firmware.md
    - thg_mobile: ./tutorials/thg_mobile.md
    - thg_social: ./tutorials/thg_social.md
    - thg_backdoor: ./tutorials/thg_backdoor.md
    - thg_decompiler: ./tutorials/thg_decompiler.md
    - thg_forensic: ./tutorials/thg_forensic.md
  - THG-PART-2:
    - thg_networking: ./tutorials/thg_networking.md
    - thg_spoff: ./tutorials/thg_spoff.md
    - thg_binary: ./tutorials/thg_binary.md
    - thg_defensensive: ./tutorials/thg_defensensive.md
    - thg_gpu: ./tutorials/thg_gpu.md
    - thg_os: ./tutorials/thg_os.md
    - thg_nfc: ./tutorials/thg_nfc.md
    - thg_spoof: ./tutorials/thg_spoof.md
    - thg_version: ./tutorials/thg_version.md
    - thg_bluetooth: ./tutorials/thg_bluetooth.md
    - thg_defensive: ./tutorials/thg_defensive.md
    - thg_hardware: ./tutorials/thg_hardware.md
    - thg_packer: ./tutorials/thg_packer.md
    - thg_stego: ./tutorials/thg_stego.md
    - thg_code_audit: ./tutorials/thg_code_audit.md
    - thg_disassembler: ./tutorials/thg_disassembler.md
    - thg_honeypot: ./tutorials/thg_honeypot.md
    - thg_proxy: ./tutorials/thg_proxy.md
    - thg_tunnel: ./tutorials/thg_tunnel.md
    - thg_cracker: ./tutorials/thg_cracker.md
    - thg_dos: ./tutorials/thg_dos.md
    - thg_ids: ./tutorials/thg_ids.md
    - thg_radio: ./tutorials/thg_radio.md
    - thg_unpacker: ./tutorials/thg_unpacker.md
- Contributing:
  - Get Started: ./contributing/get-started.md

  - LICENSE: ./LICENSE.md


